### ISSUE TITLE
Add requirements file

### ISSUE THREAD

**Issue by MarcoAGreco** [berlotto/flask-app-template#7]
Add requirements to facilitate the dependencies installation.

**Comment by quirozity** [comment]
```
pip install pipenv
pip install flask
pip install flask_bootstrap
pip install flask_sqlalchemy
pip install flask_pymongo
pip install flask_login
pip install flask_wtf
pip install WTForms==2.3.3
```

[requirements.txt](https://github.com/berlotto/flask-app-template/files/11155142/requirements.txt)

`pip install -r requirements.txt`

**Comment by berlotto** [comment]
@MarcoAGreco pipenv does it. Running `pipenv install` will install all dependencies.
